---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: ghcr-pull-secret
  namespace: gift-viewer
spec:
  path: k8s/github-registry
  keys:
    - .dockerconfigjson
  type: kubernetes.io/dockerconfigjson